#!/usr/bin/env python3
"""Persistent memory installer. Idempotent, cross-platform.

Writes two things outside the repo, both local to the machine:
  1. ~/.claude/CLAUDE.md      static import of AUTOLOAD.md      (level 1)
  2. ~/.claude/settings.json  SessionStart hook -> mem load     (level 2)

And one inside the repo, in the local git config:
  3. core.hooksPath -> install/hooks   pre-commit and pre-push block main
"""

import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CLAUDE_DIR = Path.home() / ".claude"
CLAUDE_MD = CLAUDE_DIR / "CLAUDE.md"
SETTINGS = CLAUDE_DIR / "settings.json"

START = "<!-- claude-memory:start -->"
END = "<!-- claude-memory:end -->"
BLOCK = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)


def py_cmd():
    """Interpreter for hook commands: `python` on Windows, `python3` elsewhere.

    ⚠️ **Never `sys.executable`.** Hooks run under `/usr/bin/bash`, not cmd.exe,
    and in bash a backslash is an escape: an unquoted `C:\\Python314\\python.exe`
    becomes `C:Python314python.exe` -> exit 127. The hook is non-blocking, so
    the failure surfaces nowhere and the memory silently stops loading.
    It has already happened twice. See ltm/feedback/windows-hook-quoting.md
    """
    return "python" if sys.platform == "win32" else "python3"


def hook_command(*args):
    """Hook command in bash-safe form: interpreter from PATH, script quoted with
    forward slashes, and `$HOME` rather than `~` -- which does not expand inside
    double quotes and would leave a non-existent path."""
    script = REPO / "bin" / "mem.py"
    try:
        path = "$HOME/" + script.relative_to(Path.home()).as_posix()
    except ValueError:
        path = script.as_posix()
    return " ".join([py_cmd(), f'"{path}"', *args])


def home_relative(path):
    """`~/...` when the repo lives under the home directory.

    Serves two purposes at once: it honours `portability.paths: home-relative`,
    and it keeps any space in the user name out of the text -- on Windows the
    home can be `C:\\Users\\First Last`, and an absolute path with a space is
    the first thing that breaks in tools that do not quote.
    """
    try:
        return "~/" + path.relative_to(Path.home()).as_posix()
    except ValueError:
        return path.as_posix()


def section():
    return "\n".join(
        [
            START,
            "",
            "# Persistent memory",
            "",
            f"@{home_relative(REPO / 'AUTOLOAD.md')}",
            "",
            "Full wiki index: `" + home_relative(REPO / "MEMORY.md") + "`",
            "",
            "Managed by `mem` — do not edit this block by hand, it is regenerated by `install/setup.py`.",
            "",
            END,
        ]
    )


def install_claude_md():
    CLAUDE_DIR.mkdir(parents=True, exist_ok=True)
    text = CLAUDE_MD.read_text(encoding="utf-8") if CLAUDE_MD.exists() else ""
    if BLOCK.search(text):
        text = BLOCK.sub(section(), text)
        action = "updated"
    else:
        text = (text.rstrip() + "\n\n" if text.strip() else "") + section() + "\n"
        action = "created"
    CLAUDE_MD.write_text(text, encoding="utf-8")
    print(f"  [ok] {CLAUDE_MD} — block {action}")


def install_hook():
    data = {}
    if SETTINGS.exists():
        shutil.copy2(SETTINGS, SETTINGS.with_suffix(f".json.bak-{datetime.now():%Y%m%d%H%M%S}"))
        try:
            data = json.loads(SETTINGS.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            print(f"  [!!] {SETTINGS} is not valid JSON: hook not installed")
            return


    wanted = {
        # Layer 2: global context and policy resolved against the cwd.
        "SessionStart": {
            "matcher": "startup|resume|clear",
            "hooks": [{"type": "command", "command": hook_command("load"), "timeout": 15}],
        },
        # Layer 3: the project inferred from the prompt. It exists for sessions
        # that start outside any project directory, where the cwd matches no
        # project and layer 2 would never activate the project context.
        # No `matcher`: UserPromptSubmit does not support one, it always fires.
        # Low timeout: it sits between submitting the prompt and the reply.
        "UserPromptSubmit": {
            "hooks": [{"type": "command", "command": hook_command("project", "--from-hook"), "timeout": 10}],
        },
    }

    hooks = data.setdefault("hooks", {})
    for event, entry in wanted.items():
        lst = hooks.setdefault(event, [])
        lst[:] = [e for e in lst if "mem.py" not in json.dumps(e)]
        lst.append(entry)

    SETTINGS.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    for event in wanted:
        print(f"  [ok] {SETTINGS} — {event} hook installed")
    print(f"       {cmd}")


def configure_git():
    """Never writes the git identity: it belongs to the user, not the installer.

    It only reports a missing one, and sets `init.defaultBranch` when that is
    not already defined.
    """

    def get(key):
        r = subprocess.run(["git", "config", "--global", "--get", key], capture_output=True, text=True)
        return r.stdout.strip()

    if shutil.which("git") is None:
        print("  [--] git not found, configuration skipped")
        return
    for key in ("user.name", "user.email"):
        val = get(key)
        if val:
            print(f"  [--] git {key} = {val}")
        else:
            print(f"  [!!] git {key} not set — configure it before committing")
    if not get("init.defaultBranch"):
        subprocess.run(["git", "config", "--global", "init.defaultBranch", "main"], check=False)
        print("  [ok] git init.defaultBranch = main")


def install_hooks():
    """Enables the versioned hooks on the memory repo: they block commits and pushes to main."""
    hooks = REPO / "install" / "hooks"
    if shutil.which("git") is None:
        print("  [--] git not found, hooks not enabled")
        return
    if not (REPO / ".git").exists():
        print(f"  [--] {REPO} is not a git repo, hooks not enabled")
        return
    subprocess.run(
        ["git", "-C", str(REPO), "config", "core.hooksPath", str(hooks)], check=False
    )
    for name in ("pre-commit", "pre-push"):
        path = hooks / name
        if not path.exists():
            print(f"  [!!] {name} missing in {hooks}")
            continue
        if os.name != "nt":
            path.chmod(path.stat().st_mode | 0o111)
        print(f"  [ok] {name} enabled")
    print(f"       core.hooksPath = {hooks}")


def build():
    for cmd in ("index", "graph"):
        subprocess.run([sys.executable, str(REPO / "bin" / "mem.py"), cmd], check=False)


def main():
    sys.stdout.reconfigure(line_buffering=True)
    print(f"claude-memory · installing from {REPO}\n")
    print("git:")
    configure_git()
    print("\ngit hooks (main blocked):")
    install_hooks()
    print("\nautoload level 1 (static):")
    install_claude_md()
    print("\nautoload level 2 (hook):")
    install_hook()
    print("\nindex:")
    build()
    print("\nDone. Verify with:")
    print(f"  {hook_command('doctor')}")


if __name__ == "__main__":
    main()
